version: "3.9"

services:
  php:
    image: php:8.2-fpm
    restart: always
    container_name: app
    tty: true
    environment:
      APP_ENV: dev
    working_dir: /var/www/html
    command: php-fpm
    volumes:
      - ./:/var/www/html:rw
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx
    ports:
      - 9000:9000
    networks:
      - app-network

  composer:
    image: composer:2
    container_name: composer
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
    command: sh -c "composer install --prefer-dist"
    networks:
      - app-network

  node:
    image: node:19.7.0-alpine
    container_name: node
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
    command: sh -c "npm install && npm install -g npm@latest && npm run dev"
    networks:
      - app-network
  
  #Webserver
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network: